// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enabled": boolean;
      "types.highlight": boolean;
      "types.underline": boolean;
      "types.note": boolean;
      "types.text": boolean;
      "types.image": boolean;
      "compactNoteIcons": boolean;
    };
  }
}
